# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: /
    weight: 10
  - name: Projects
    url: projects/
    weight: 20
  - name: Topics
    url: topics/
    weight: 30
  - name: Education
    url: education/
    weight: 40
